import { Metadata } from 'next';
import { Box, Container, Typography, Paper } from '@mui/material';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Terms of Service - Fat2Fit',
  description: 'Terms of Service and user agreements for the Fat2Fit application.',
};

export default function TermsOfServicePage() {
  return (
    <Box sx={{ minHeight: '100vh', py: 8, bgcolor: 'background.default' }}>
      <Container maxWidth="md">
        <Typography variant="h3" component="h1" gutterBottom align="center" sx={{ fontWeight: 'bold' }}>
          Terms of Service
        </Typography>
        <Typography variant="subtitle1" color="text.secondary" align="center" gutterBottom sx={{ mb: 6 }}>
          Last Updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
        </Typography>

        <Paper elevation={0} variant="outlined" sx={{ p: { xs: 3, md: 5 }, borderRadius: 2 }}>
          <Box sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
              1. Acceptance of Terms
            </Typography>
            <Typography variant="body1" paragraph>
              By downloading, installing, accessing, or using the Fat2Fit mobile application and associated website, you agree to comply with and be bound by these Terms of Service. If you do not agree to these terms, please do not use our services.
            </Typography>
          </Box>

          <Box sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
              2. Account Creation and Usage Rules
            </Typography>
            <Typography variant="body1" paragraph>
              To fully utilize the application, you must create an account. When setting up an account, you must provide accurate, complete, and updated information. This includes your:
            </Typography>
            <Typography component="div" variant="body1" sx={{ ml: 4, mb: 2 }}>
              <ul>
                <li><strong>Full Name</strong></li>
                <li><strong>Email Address</strong> (used for communication and login security)</li>
                <li><strong>Height, Weight, and Sex</strong> (used strictly and exclusively for generating personalized physiological metrics and routines)</li>
              </ul>
            </Typography>
            <Typography variant="body1" paragraph>
              You are entirely responsible for maintaining the confidentiality of your account login information and for all activities that occur under your account. Refer to our <Link href="/privacy-policy" style={{ color: 'inherit', textDecoration: 'underline' }}>Privacy Policy</Link> to learn how we protect this information using AES 256 database encryption.
            </Typography>
          </Box>

          <Box sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
              3. Medical Disclaimer
            </Typography>
            <Typography variant="body1" color="error.main" sx={{ fontWeight: 'bold', mb: 1 }}>
              Always seek the advice of a qualified health provider with any questions you may have regarding a medical condition before starting any new diet, fitness, or exercise program.
            </Typography>
            <Typography variant="body1" paragraph>
              Fat2Fit does not provide professional medical advice, diagnosis, or treatment. The application is designed for informational and educational purposes primarily focused on fitness and metabolic optimization. Using the fitness regimens generated by our systems is entirely at your own risk.
            </Typography>
          </Box>
          
          <Box sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
              4. User Conduct
            </Typography>
            <Typography variant="body1" paragraph>
              As a user of the Fat2Fit application, you agree not to:
            </Typography>
            <Typography component="div" variant="body1" sx={{ ml: 4, mb: 2 }}>
              <ul>
                <li>Submit false, misleading, or inappropriate information.</li>
                <li>Utilize the platform in ways that could disable, damage, or systematically disrupt the application functionality.</li>
                <li>Attempt to reverse engineer, decompile, or hack the service or its AES-encrypted databases.</li>
                <li>Transfer or sell your account to third parties.</li>
              </ul>
            </Typography>
          </Box>

          <Box sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
              5. Limitation of Liability
            </Typography>
            <Typography variant="body1" paragraph>
              To the absolute extent permitted by applicable law, Fat2Fit and its developers shall not be liable for any direct, indirect, incidental, special, consequential, or exemplary injuries or damages resulting from the use or inability to use the service, the cost of procurement of substitute goods and services, or any goods or services purchased or obtained horizontally through our service.
            </Typography>
          </Box>

          <Box sx={{ mb: 4 }}>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
              6. Modifications to the Service
            </Typography>
            <Typography variant="body1" paragraph>
              Fat2Fit reserves the intrinsic right to modify or discontinue, temporarily or permanently, the service (or any part thereof) with or without reasonable prior notice to users.
            </Typography>
          </Box>

          <Box>
            <Typography variant="h5" component="h2" gutterBottom sx={{ fontWeight: 600 }}>
              7. Contact Information
            </Typography>
            <Typography variant="body1" paragraph>
              Any inquiries regarding the present Terms of Service should be electronically directed to contact@fat2fitxpress.com.
            </Typography>
          </Box>
        </Paper>
      </Container>
    </Box>
  );
}
